apiVersion: v2
description: SSCS - CCD Definitions
name: sscs-ccd-definitions
version: 0.0.8
dependencies:
  - name: nodejs
    version: 18.16.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
